<?php
/**
 * AppConfigUpdateModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Flipdish\\Client;

/**
 * AppConfigUpdateModelTest Class Doc Comment
 *
 * @category    Class
 * @description Application configuration
 * @package     Flipdish\\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AppConfigUpdateModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AppConfigUpdateModel"
     */
    public function testAppConfigUpdateModel()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "host_name"
     */
    public function testPropertyHostName()
    {
    }

    /**
     * Test attribute "main_color"
     */
    public function testPropertyMainColor()
    {
    }

    /**
     * Test attribute "kiosk_primary_colour"
     */
    public function testPropertyKioskPrimaryColour()
    {
    }

    /**
     * Test attribute "application_category"
     */
    public function testPropertyApplicationCategory()
    {
    }

    /**
     * Test attribute "is_panacea_enabled"
     */
    public function testPropertyIsPanaceaEnabled()
    {
    }

    /**
     * Test attribute "cookie_consent_prompt_enabled"
     */
    public function testPropertyCookieConsentPromptEnabled()
    {
    }
}
