<?php
/**
 * AppInstallTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Flipdish\\Client;

/**
 * AppInstallTest Class Doc Comment
 *
 * @category    Class
 * @description App Install information
 * @package     Flipdish\\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AppInstallTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AppInstall"
     */
    public function testAppInstall()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "first_login"
     */
    public function testPropertyFirstLogin()
    {
    }

    /**
     * Test attribute "first_login_human"
     */
    public function testPropertyFirstLoginHuman()
    {
    }

    /**
     * Test attribute "last_activity"
     */
    public function testPropertyLastActivity()
    {
    }

    /**
     * Test attribute "last_activity_human"
     */
    public function testPropertyLastActivityHuman()
    {
    }

    /**
     * Test attribute "google_tokens"
     */
    public function testPropertyGoogleTokens()
    {
    }

    /**
     * Test attribute "apple_tokens"
     */
    public function testPropertyAppleTokens()
    {
    }

    /**
     * Test attribute "order_count"
     */
    public function testPropertyOrderCount()
    {
    }

    /**
     * Test attribute "user_agent_at_signup"
     */
    public function testPropertyUserAgentAtSignup()
    {
    }

    /**
     * Test attribute "user_agent_most_recent"
     */
    public function testPropertyUserAgentMostRecent()
    {
    }
}
