<?php
/**
 * AppStoreAppConfigurationSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Flipdish\\Client;

/**
 * AppStoreAppConfigurationSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description App store app configuration summary information
 * @package     Flipdish\\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AppStoreAppConfigurationSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AppStoreAppConfigurationSummary"
     */
    public function testAppStoreAppConfigurationSummary()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "app_id"
     */
    public function testPropertyAppId()
    {
    }

    /**
     * Test attribute "is_enabled"
     */
    public function testPropertyIsEnabled()
    {
    }

    /**
     * Test attribute "stores"
     */
    public function testPropertyStores()
    {
    }

    /**
     * Test attribute "configuration_type"
     */
    public function testPropertyConfigurationType()
    {
    }

    /**
     * Test attribute "store_selector_type"
     */
    public function testPropertyStoreSelectorType()
    {
    }

    /**
     * Test attribute "internal"
     */
    public function testPropertyInternal()
    {
    }

    /**
     * Test attribute "app_store_app_id"
     */
    public function testPropertyAppStoreAppId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }

    /**
     * Test attribute "developer_name"
     */
    public function testPropertyDeveloperName()
    {
    }
}
