<?php
/**
 * BusinessHoursPeriodBaseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Flipdish\Client;

/**
 * BusinessHoursPeriodBaseTest Class Doc Comment
 *
 * @category    Class
 * @description Business hours period
 * @package     Flipdish\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BusinessHoursPeriodBaseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BusinessHoursPeriodBase"
     */
    public function testBusinessHoursPeriodBase()
    {
    }

    /**
     * Test attribute "day_of_week"
     */
    public function testPropertyDayOfWeek()
    {
    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {
    }

    /**
     * Test attribute "period"
     */
    public function testPropertyPeriod()
    {
    }

    /**
     * Test attribute "start_time_early"
     */
    public function testPropertyStartTimeEarly()
    {
    }

    /**
     * Test attribute "period_early"
     */
    public function testPropertyPeriodEarly()
    {
    }
}
