<?php
/**
 * EmvTerminalWithAssignmentsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Flipdish\\Client;

/**
 * EmvTerminalWithAssignmentsTest Class Doc Comment
 *
 * @category    Class
 * @description EMV Payment Terminal
 * @package     Flipdish\\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmvTerminalWithAssignmentsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmvTerminalWithAssignments"
     */
    public function testEmvTerminalWithAssignments()
    {
    }

    /**
     * Test attribute "emv_terminal_id"
     */
    public function testPropertyEmvTerminalId()
    {
    }

    /**
     * Test attribute "terminal_id"
     */
    public function testPropertyTerminalId()
    {
    }

    /**
     * Test attribute "is_assigned_to_hydra_device"
     */
    public function testPropertyIsAssignedToHydraDevice()
    {
    }

    /**
     * Test attribute "hydra_config_id"
     */
    public function testPropertyHydraConfigId()
    {
    }

    /**
     * Test attribute "hydra_device_id"
     */
    public function testPropertyHydraDeviceId()
    {
    }

    /**
     * Test attribute "hydra_name"
     */
    public function testPropertyHydraName()
    {
    }
}
