<?php
/**
 * HydraDeviceDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Flipdish\\Client;

/**
 * HydraDeviceDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description Hydra device details
 * @package     Flipdish\\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HydraDeviceDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HydraDeviceDetails"
     */
    public function testHydraDeviceDetails()
    {
    }

    /**
     * Test attribute "hydra_config_id"
     */
    public function testPropertyHydraConfigId()
    {
    }

    /**
     * Test attribute "device_id"
     */
    public function testPropertyDeviceId()
    {
    }

    /**
     * Test attribute "serial_number"
     */
    public function testPropertySerialNumber()
    {
    }

    /**
     * Test attribute "device_type"
     */
    public function testPropertyDeviceType()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "device_name"
     */
    public function testPropertyDeviceName()
    {
    }

    /**
     * Test attribute "store_names"
     */
    public function testPropertyStoreNames()
    {
    }

    /**
     * Test attribute "last_poll_utc"
     */
    public function testPropertyLastPollUtc()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "build_number"
     */
    public function testPropertyBuildNumber()
    {
    }

    /**
     * Test attribute "git_sha"
     */
    public function testPropertyGitSha()
    {
    }

    /**
     * Test attribute "git_branch"
     */
    public function testPropertyGitBranch()
    {
    }
}
