<?php
/**
 * PayoutReport3DetailsAdjustmentsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Flipdish\\Client;

/**
 * PayoutReport3DetailsAdjustmentsTest Class Doc Comment
 *
 * @category    Class
 * @description PayoutReport3DetailsAdjustments
 * @package     Flipdish\\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PayoutReport3DetailsAdjustmentsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PayoutReport3DetailsAdjustments"
     */
    public function testPayoutReport3DetailsAdjustments()
    {
    }

    /**
     * Test attribute "opening_balance_date"
     */
    public function testPropertyOpeningBalanceDate()
    {
    }

    /**
     * Test attribute "closing_balance_date"
     */
    public function testPropertyClosingBalanceDate()
    {
    }

    /**
     * Test attribute "opening_balance"
     */
    public function testPropertyOpeningBalance()
    {
    }

    /**
     * Test attribute "refunds_on_card_orders"
     */
    public function testPropertyRefundsOnCardOrders()
    {
    }

    /**
     * Test attribute "refunds_on_cash_orders"
     */
    public function testPropertyRefundsOnCashOrders()
    {
    }

    /**
     * Test attribute "cash_customer_fees"
     */
    public function testPropertyCashCustomerFees()
    {
    }

    /**
     * Test attribute "chargebacks"
     */
    public function testPropertyChargebacks()
    {
    }

    /**
     * Test attribute "other_transactions"
     */
    public function testPropertyOtherTransactions()
    {
    }

    /**
     * Test attribute "closing_balance"
     */
    public function testPropertyClosingBalance()
    {
    }

    /**
     * Test attribute "balance_repaid"
     */
    public function testPropertyBalanceRepaid()
    {
    }

    /**
     * Test attribute "refunds_on_card_orders_brackets_amount"
     */
    public function testPropertyRefundsOnCardOrdersBracketsAmount()
    {
    }

    /**
     * Test attribute "refunds_on_card_orders_brackets_out_of_amount"
     */
    public function testPropertyRefundsOnCardOrdersBracketsOutOfAmount()
    {
    }

    /**
     * Test attribute "refunds_on_cash_orders_brackets_amount"
     */
    public function testPropertyRefundsOnCashOrdersBracketsAmount()
    {
    }

    /**
     * Test attribute "refunds_on_cash_orders_brackets_out_of_amount"
     */
    public function testPropertyRefundsOnCashOrdersBracketsOutOfAmount()
    {
    }

    /**
     * Test attribute "cash_customer_fees_brackets_amount"
     */
    public function testPropertyCashCustomerFeesBracketsAmount()
    {
    }

    /**
     * Test attribute "cash_customer_fees_brackets_out_of_amount"
     */
    public function testPropertyCashCustomerFeesBracketsOutOfAmount()
    {
    }

    /**
     * Test attribute "balance_change"
     */
    public function testPropertyBalanceChange()
    {
    }

    /**
     * Test attribute "previous_payout_id"
     */
    public function testPropertyPreviousPayoutId()
    {
    }

    /**
     * Test attribute "next_payout_id"
     */
    public function testPropertyNextPayoutId()
    {
    }

    /**
     * Test attribute "refunded_fees_on_chargebacks"
     */
    public function testPropertyRefundedFeesOnChargebacks()
    {
    }

    /**
     * Test attribute "total_chargeback_cost"
     */
    public function testPropertyTotalChargebackCost()
    {
    }
}
