<?php
/**
 * PayoutReport3DetailsSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Flipdish\\Client;

/**
 * PayoutReport3DetailsSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description PayoutReport3DetailsSummary
 * @package     Flipdish\\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PayoutReport3DetailsSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PayoutReport3DetailsSummary"
     */
    public function testPayoutReport3DetailsSummary()
    {
    }

    /**
     * Test attribute "revenue"
     */
    public function testPropertyRevenue()
    {
    }

    /**
     * Test attribute "revenue_of_which_cash"
     */
    public function testPropertyRevenueOfWhichCash()
    {
    }

    /**
     * Test attribute "revenue_for_fee_calculations"
     */
    public function testPropertyRevenueForFeeCalculations()
    {
    }

    /**
     * Test attribute "flipdish_fees"
     */
    public function testPropertyFlipdishFees()
    {
    }

    /**
     * Test attribute "adjustments"
     */
    public function testPropertyAdjustments()
    {
    }

    /**
     * Test attribute "third_party_integration_fees_and_tips"
     */
    public function testPropertyThirdPartyIntegrationFeesAndTips()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }
}
