<?php
/**
 * PreviousOrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Flipdish\\Client;

/**
 * PreviousOrderTest Class Doc Comment
 *
 * @category    Class
 * @description PreviousOrder
 * @package     Flipdish\\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PreviousOrderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PreviousOrder"
     */
    public function testPreviousOrder()
    {
    }

    /**
     * Test attribute "delivery_type"
     */
    public function testPropertyDeliveryType()
    {
    }

    /**
     * Test attribute "delivery_location_address_string"
     */
    public function testPropertyDeliveryLocationAddressString()
    {
    }

    /**
     * Test attribute "payment_account_type"
     */
    public function testPropertyPaymentAccountType()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "restaurant_name"
     */
    public function testPropertyRestaurantName()
    {
    }

    /**
     * Test attribute "local_order_id"
     */
    public function testPropertyLocalOrderId()
    {
    }

    /**
     * Test attribute "table_service_category"
     */
    public function testPropertyTableServiceCategory()
    {
    }

    /**
     * Test attribute "pickup_location_option_value"
     */
    public function testPropertyPickupLocationOptionValue()
    {
    }

    /**
     * Test attribute "customer_name"
     */
    public function testPropertyCustomerName()
    {
    }

    /**
     * Test attribute "phone_number_international_format_string"
     */
    public function testPropertyPhoneNumberInternationalFormatString()
    {
    }

    /**
     * Test attribute "delivery_instructions"
     */
    public function testPropertyDeliveryInstructions()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "processing_fee"
     */
    public function testPropertyProcessingFee()
    {
    }

    /**
     * Test attribute "service_charge_percentage"
     */
    public function testPropertyServiceChargePercentage()
    {
    }

    /**
     * Test attribute "service_charge_amount"
     */
    public function testPropertyServiceChargeAmount()
    {
    }

    /**
     * Test attribute "tip_amount"
     */
    public function testPropertyTipAmount()
    {
    }

    /**
     * Test attribute "delivery_amount"
     */
    public function testPropertyDeliveryAmount()
    {
    }

    /**
     * Test attribute "total_tax"
     */
    public function testPropertyTotalTax()
    {
    }

    /**
     * Test attribute "total_amount"
     */
    public function testPropertyTotalAmount()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }

    /**
     * Test attribute "tax_rates"
     */
    public function testPropertyTaxRates()
    {
    }

    /**
     * Test attribute "white_label_id"
     */
    public function testPropertyWhiteLabelId()
    {
    }
}
