<?php
/**
 * RestaurantTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Flipdish\\Client;

/**
 * RestaurantTest Class Doc Comment
 *
 * @category    Class
 * @description Restaurant search result
 * @package     Flipdish\\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RestaurantTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Restaurant"
     */
    public function testRestaurant()
    {
    }

    /**
     * Test attribute "white_label_configs"
     */
    public function testPropertyWhiteLabelConfigs()
    {
    }

    /**
     * Test attribute "virtual_restaurant_id"
     */
    public function testPropertyVirtualRestaurantId()
    {
    }

    /**
     * Test attribute "virtual_restaurant_name"
     */
    public function testPropertyVirtualRestaurantName()
    {
    }

    /**
     * Test attribute "virtual_restaurant_url"
     */
    public function testPropertyVirtualRestaurantUrl()
    {
    }

    /**
     * Test attribute "physical_restaurant_id"
     */
    public function testPropertyPhysicalRestaurantId()
    {
    }

    /**
     * Test attribute "physical_restaurant_name"
     */
    public function testPropertyPhysicalRestaurantName()
    {
    }

    /**
     * Test attribute "physical_restaurant_address"
     */
    public function testPropertyPhysicalRestaurantAddress()
    {
    }

    /**
     * Test attribute "menu_id"
     */
    public function testPropertyMenuId()
    {
    }

    /**
     * Test attribute "is_archived"
     */
    public function testPropertyIsArchived()
    {
    }

    /**
     * Test attribute "is_published"
     */
    public function testPropertyIsPublished()
    {
    }

    /**
     * Test attribute "flipdish_stripe_custom_connected_accounts"
     */
    public function testPropertyFlipdishStripeCustomConnectedAccounts()
    {
    }
}
