<?php
/**
 * StoreKioskSettingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Flipdish\\Client;

/**
 * StoreKioskSettingTest Class Doc Comment
 *
 * @category    Class
 * @description Store Kiosk Settings
 * @package     Flipdish\\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StoreKioskSettingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StoreKioskSetting"
     */
    public function testStoreKioskSetting()
    {
    }

    /**
     * Test attribute "kiosk_setting_id"
     */
    public function testPropertyKioskSettingId()
    {
    }

    /**
     * Test attribute "kiosk_name"
     */
    public function testPropertyKioskName()
    {
    }

    /**
     * Test attribute "require_customer_name"
     */
    public function testPropertyRequireCustomerName()
    {
    }

    /**
     * Test attribute "require_customer_phone_number"
     */
    public function testPropertyRequireCustomerPhoneNumber()
    {
    }

    /**
     * Test attribute "request_customer_phone_number"
     */
    public function testPropertyRequestCustomerPhoneNumber()
    {
    }

    /**
     * Test attribute "request_table_number"
     */
    public function testPropertyRequestTableNumber()
    {
    }

    /**
     * Test attribute "offer_dine_in_or_takeaway_option"
     */
    public function testPropertyOfferDineInOrTakeawayOption()
    {
    }

    /**
     * Test attribute "physical_restaurant_id"
     */
    public function testPropertyPhysicalRestaurantId()
    {
    }

    /**
     * Test attribute "hydra_config_id"
     */
    public function testPropertyHydraConfigId()
    {
    }
}
