<?php
/**
 * StoreKioskSetting
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Flipdish\\Client\Models;

use \ArrayAccess;
use \Flipdish\\Client\ObjectSerializer;

/**
 * StoreKioskSetting Class Doc Comment
 *
 * @category Class
 * @description Store Kiosk Settings
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StoreKioskSetting implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'StoreKioskSetting';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'kiosk_setting_id' => 'int',
        'kiosk_name' => 'string',
        'require_customer_name' => 'bool',
        'require_customer_phone_number' => 'bool',
        'request_customer_phone_number' => 'bool',
        'request_table_number' => 'bool',
        'offer_dine_in_or_takeaway_option' => 'bool',
        'physical_restaurant_id' => 'int',
        'hydra_config_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'kiosk_setting_id' => 'int32',
        'kiosk_name' => null,
        'require_customer_name' => null,
        'require_customer_phone_number' => null,
        'request_customer_phone_number' => null,
        'request_table_number' => null,
        'offer_dine_in_or_takeaway_option' => null,
        'physical_restaurant_id' => 'int32',
        'hydra_config_id' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kiosk_setting_id' => 'KioskSettingId',
        'kiosk_name' => 'KioskName',
        'require_customer_name' => 'RequireCustomerName',
        'require_customer_phone_number' => 'RequireCustomerPhoneNumber',
        'request_customer_phone_number' => 'RequestCustomerPhoneNumber',
        'request_table_number' => 'RequestTableNumber',
        'offer_dine_in_or_takeaway_option' => 'OfferDineInOrTakeawayOption',
        'physical_restaurant_id' => 'PhysicalRestaurantId',
        'hydra_config_id' => 'HydraConfigId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kiosk_setting_id' => 'setKioskSettingId',
        'kiosk_name' => 'setKioskName',
        'require_customer_name' => 'setRequireCustomerName',
        'require_customer_phone_number' => 'setRequireCustomerPhoneNumber',
        'request_customer_phone_number' => 'setRequestCustomerPhoneNumber',
        'request_table_number' => 'setRequestTableNumber',
        'offer_dine_in_or_takeaway_option' => 'setOfferDineInOrTakeawayOption',
        'physical_restaurant_id' => 'setPhysicalRestaurantId',
        'hydra_config_id' => 'setHydraConfigId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kiosk_setting_id' => 'getKioskSettingId',
        'kiosk_name' => 'getKioskName',
        'require_customer_name' => 'getRequireCustomerName',
        'require_customer_phone_number' => 'getRequireCustomerPhoneNumber',
        'request_customer_phone_number' => 'getRequestCustomerPhoneNumber',
        'request_table_number' => 'getRequestTableNumber',
        'offer_dine_in_or_takeaway_option' => 'getOfferDineInOrTakeawayOption',
        'physical_restaurant_id' => 'getPhysicalRestaurantId',
        'hydra_config_id' => 'getHydraConfigId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['kiosk_setting_id'] = isset($data['kiosk_setting_id']) ? $data['kiosk_setting_id'] : null;
        $this->container['kiosk_name'] = isset($data['kiosk_name']) ? $data['kiosk_name'] : null;
        $this->container['require_customer_name'] = isset($data['require_customer_name']) ? $data['require_customer_name'] : null;
        $this->container['require_customer_phone_number'] = isset($data['require_customer_phone_number']) ? $data['require_customer_phone_number'] : null;
        $this->container['request_customer_phone_number'] = isset($data['request_customer_phone_number']) ? $data['request_customer_phone_number'] : null;
        $this->container['request_table_number'] = isset($data['request_table_number']) ? $data['request_table_number'] : null;
        $this->container['offer_dine_in_or_takeaway_option'] = isset($data['offer_dine_in_or_takeaway_option']) ? $data['offer_dine_in_or_takeaway_option'] : null;
        $this->container['physical_restaurant_id'] = isset($data['physical_restaurant_id']) ? $data['physical_restaurant_id'] : null;
        $this->container['hydra_config_id'] = isset($data['hydra_config_id']) ? $data['hydra_config_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kiosk_setting_id
     *
     * @return int
     */
    public function getKioskSettingId()
    {
        return $this->container['kiosk_setting_id'];
    }

    /**
     * Sets kiosk_setting_id
     *
     * @param int $kiosk_setting_id Kiosk setting id
     *
     * @return $this
     */
    public function setKioskSettingId($kiosk_setting_id)
    {
        $this->container['kiosk_setting_id'] = $kiosk_setting_id;

        return $this;
    }

    /**
     * Gets kiosk_name
     *
     * @return string
     */
    public function getKioskName()
    {
        return $this->container['kiosk_name'];
    }

    /**
     * Sets kiosk_name
     *
     * @param string $kiosk_name Store kiosk name
     *
     * @return $this
     */
    public function setKioskName($kiosk_name)
    {
        $this->container['kiosk_name'] = $kiosk_name;

        return $this;
    }

    /**
     * Gets require_customer_name
     *
     * @return bool
     */
    public function getRequireCustomerName()
    {
        return $this->container['require_customer_name'];
    }

    /**
     * Sets require_customer_name
     *
     * @param bool $require_customer_name Require customer name flag
     *
     * @return $this
     */
    public function setRequireCustomerName($require_customer_name)
    {
        $this->container['require_customer_name'] = $require_customer_name;

        return $this;
    }

    /**
     * Gets require_customer_phone_number
     *
     * @return bool
     */
    public function getRequireCustomerPhoneNumber()
    {
        return $this->container['require_customer_phone_number'];
    }

    /**
     * Sets require_customer_phone_number
     *
     * @param bool $require_customer_phone_number Require customer phone number flag
     *
     * @return $this
     */
    public function setRequireCustomerPhoneNumber($require_customer_phone_number)
    {
        $this->container['require_customer_phone_number'] = $require_customer_phone_number;

        return $this;
    }

    /**
     * Gets request_customer_phone_number
     *
     * @return bool
     */
    public function getRequestCustomerPhoneNumber()
    {
        return $this->container['request_customer_phone_number'];
    }

    /**
     * Sets request_customer_phone_number
     *
     * @param bool $request_customer_phone_number Request customer phone number flag (Option to Skip)
     *
     * @return $this
     */
    public function setRequestCustomerPhoneNumber($request_customer_phone_number)
    {
        $this->container['request_customer_phone_number'] = $request_customer_phone_number;

        return $this;
    }

    /**
     * Gets request_table_number
     *
     * @return bool
     */
    public function getRequestTableNumber()
    {
        return $this->container['request_table_number'];
    }

    /**
     * Sets request_table_number
     *
     * @param bool $request_table_number Request table number flag
     *
     * @return $this
     */
    public function setRequestTableNumber($request_table_number)
    {
        $this->container['request_table_number'] = $request_table_number;

        return $this;
    }

    /**
     * Gets offer_dine_in_or_takeaway_option
     *
     * @return bool
     */
    public function getOfferDineInOrTakeawayOption()
    {
        return $this->container['offer_dine_in_or_takeaway_option'];
    }

    /**
     * Sets offer_dine_in_or_takeaway_option
     *
     * @param bool $offer_dine_in_or_takeaway_option Offer Dine-In/Takeaway option flag
     *
     * @return $this
     */
    public function setOfferDineInOrTakeawayOption($offer_dine_in_or_takeaway_option)
    {
        $this->container['offer_dine_in_or_takeaway_option'] = $offer_dine_in_or_takeaway_option;

        return $this;
    }

    /**
     * Gets physical_restaurant_id
     *
     * @return int
     */
    public function getPhysicalRestaurantId()
    {
        return $this->container['physical_restaurant_id'];
    }

    /**
     * Sets physical_restaurant_id
     *
     * @param int $physical_restaurant_id Physical restaurant id
     *
     * @return $this
     */
    public function setPhysicalRestaurantId($physical_restaurant_id)
    {
        $this->container['physical_restaurant_id'] = $physical_restaurant_id;

        return $this;
    }

    /**
     * Gets hydra_config_id
     *
     * @return int
     */
    public function getHydraConfigId()
    {
        return $this->container['hydra_config_id'];
    }

    /**
     * Sets hydra_config_id
     *
     * @param int $hydra_config_id Hydra config id
     *
     * @return $this
     */
    public function setHydraConfigId($hydra_config_id)
    {
        $this->container['hydra_config_id'] = $hydra_config_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


