<?php
/**
 * AppStoreDeveloperApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Flipdish\\Client;

use \Flipdish\\Client\Configuration;
use \Flipdish\\Client\ApiException;
use \Flipdish\\Client\ObjectSerializer;

/**
 * AppStoreDeveloperApiTest Class Doc Comment
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppStoreDeveloperApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for appVerificationUpdate
     *
     * .
     *
     */
    public function testAppVerificationUpdate()
    {
    }

    /**
     * Test case for createAppStoreApp
     *
     * .
     *
     */
    public function testCreateAppStoreApp()
    {
    }

    /**
     * Test case for deleteAppStoreApp
     *
     * .
     *
     */
    public function testDeleteAppStoreApp()
    {
    }

    /**
     * Test case for getAppExternalProduct
     *
     * .
     *
     */
    public function testGetAppExternalProduct()
    {
    }

    /**
     * Test case for getExternalFunctionSigningKey
     *
     * .
     *
     */
    public function testGetExternalFunctionSigningKey()
    {
    }

    /**
     * Test case for updateAppStoreApp
     *
     * .
     *
     */
    public function testUpdateAppStoreApp()
    {
    }

    /**
     * Test case for updateExternalProduct
     *
     * .
     *
     */
    public function testUpdateExternalProduct()
    {
    }

    /**
     * Test case for uploadAppStoreAppLogo
     *
     * .
     *
     */
    public function testUploadAppStoreAppLogo()
    {
    }
}
