<?php
/**
 * MenuSectionItemsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Flipdish\\Client;

use \Flipdish\\Client\Configuration;
use \Flipdish\\Client\ApiException;
use \Flipdish\\Client\ObjectSerializer;

/**
 * MenuSectionItemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Flipdish\\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MenuSectionItemsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cloneMenuSectionItem
     *
     * .
     *
     */
    public function testCloneMenuSectionItem()
    {
    }

    /**
     * Test case for createMenuSectionItem
     *
     * .
     *
     */
    public function testCreateMenuSectionItem()
    {
    }

    /**
     * Test case for createMenuSectionItemFromCatalogItems
     *
     * .
     *
     */
    public function testCreateMenuSectionItemFromCatalogItems()
    {
    }

    /**
     * Test case for deleteMenuSectionItem
     *
     * .
     *
     */
    public function testDeleteMenuSectionItem()
    {
    }

    /**
     * Test case for deleteMenuSectionItemImage
     *
     * .
     *
     */
    public function testDeleteMenuSectionItemImage()
    {
    }

    /**
     * Test case for getMenuItemById
     *
     * Get menu item by identifier.
     *
     */
    public function testGetMenuItemById()
    {
    }

    /**
     * Test case for getMenuItems
     *
     * Get menu items.
     *
     */
    public function testGetMenuItems()
    {
    }

    /**
     * Test case for moveMenuItem
     *
     * .
     *
     */
    public function testMoveMenuItem()
    {
    }

    /**
     * Test case for setSectionItemTax
     *
     * .
     *
     */
    public function testSetSectionItemTax()
    {
    }

    /**
     * Test case for updateMenuSectionItem
     *
     * .
     *
     */
    public function testUpdateMenuSectionItem()
    {
    }

    /**
     * Test case for uploadMenuSectionItemImage
     *
     * .
     *
     */
    public function testUploadMenuSectionItemImage()
    {
    }
}
